### ISSUE TITLE
Hacking my way to talking to Jesper 

### ISSUE THREAD

**Issue by andreeahutu** [monta-app/static#31]
@JesperTerkelsen  cannot access my LinkedIn and have no other way to contact you ( the invite didn’t make it to my email andreea.hutu@gmail.com). I am stuck in Paris so cannot come visit Monta

**Comment by JesperTerkelsen** [comment]
No worries

Let’s find another date

/Jesper

Sincerely,

Jesper Terkelsen

VP Engineering

***@***.***

  <http://monta.com>

   <https://www.linkedin.com/company/montaapp>

   <https://www.instagram.com/montadotcom/>
